---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directories:
      - /
      - /modules/*
    schedule:
      interval: monthly
    groups:
      b2-provider:
        patterns:
          - Backblaze/b2
      github-provider:
        patterns:
          - integrations/github
      scaleway-provider:
        patterns:
          - scaleway/scaleway
      time-provider:
        patterns:
          - hashicorp/time
      vultr-provider:
        patterns:
          - vultr/vultr
      other-providers:
        patterns:
          - "*"
