---
version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: infrastructure

  - package-ecosystem: terraform
    directories:
      - /
      - /modules/*
    multi-ecosystem-group: infrastructure
